ubsApp.transferToBankConfig={
    "transferToBank":{
		"category":"TransferToBank",
		"templates":[
		{
			"templateId":11,
			"questionId": "TransferToBank",
			"templateType":"transfer",
			"title":"{{transferToBankTitle}}",
			"cashTitle":"{{cashTitle}}",
			"bankBalanceTitle":"{{bankBalanceTitle}}",
			"transferTitle":"{{transferTitle}}",		
			"amountToTransferTitle":"{{amountToTransferTitle}}",
			"cancelTitle":"{{cancelTitle}}",
			"transfer":true,
		}
	]
	},
}